import { useEffect, useRef, useState } from 'react'
import * as THREE from 'three'
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js'

const COLOR_STOPS=[[.02,.11,.28],[.02,.56,.76],[.18,.82,.66],[.97,.79,.25],[.9,.2,.12]]
function writeColor(target,index,t){const q=Math.max(0,Math.min(.999,t))*(COLOR_STOPS.length-1),i=Math.floor(q),f=q-i,a=COLOR_STOPS[i],b=COLOR_STOPS[Math.min(i+1,COLOR_STOPS.length-1)];target[index*3]=a[0]+(b[0]-a[0])*f;target[index*3+1]=a[1]+(b[1]-a[1])*f;target[index*3+2]=a[2]+(b[2]-a[2])*f}
function normalizeVector(vx,vy,vz){const n=Math.hypot(vx,vy,vz)||1;return[vx/n,vy/n,vz/n]}
function displayPoint(point,bounds){const spans=['x','y','z'].map((key,i)=>Math.max(1e-12,bounds[key][1]-bounds[key][0])),maxSpan=Math.max(...spans),scale=5.5/maxSpan;return[(point.x-(bounds.x[0]+bounds.x[1])/2)*scale,(point.z-(bounds.z[0]+bounds.z[1])/2)*scale,(point.y-(bounds.y[0]+bounds.y[1])/2)*scale]}

function geometryFor(model,scene,bounds){const group=new THREE.Group(),sx=bounds.x[1]-bounds.x[0],sy=bounds.y[1]-bounds.y[0],sz=bounds.z[1]-bounds.z[0],max=Math.max(sx,sy,sz),scale=5.5/max,wire=new THREE.MeshBasicMaterial({color:0x5f8299,wireframe:true,transparent:true,opacity:.2})
  if(model==='plasma'){const torus=new THREE.Mesh(new THREE.TorusGeometry(2,.78,22,96),wire);torus.rotation.x=Math.PI/2;group.add(torus);for(let i=0;i<16;i++){const coil=new THREE.Mesh(new THREE.TorusGeometry(2.75,.045,8,80),new THREE.MeshBasicMaterial({color:0x607fa0,transparent:true,opacity:.48}));coil.rotation.set(Math.PI/2,0,i*Math.PI/8);group.add(coil)}}
  else if(model==='em'){const radius=sx*.5*scale/2.25,length=sz*scale/2.9;for(let i=0;i<22;i++){const ring=new THREE.Mesh(new THREE.TorusGeometry(radius,.018,8,64),new THREE.MeshBasicMaterial({color:0xc47f42,transparent:true,opacity:.75}));ring.rotation.x=Math.PI/2;ring.position.y=-length/2+i/21*length;group.add(ring)}}
  else if(model==='gas'){const radius=Math.min(sx,sy)*.085*scale*4;const cylinder=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,sz*scale,48,1,true),wire);cylinder.rotation.x=Math.PI/2;group.add(cylinder)}
  else if(model==='pipe'){const radius=Math.max(sy,sz)*.5*scale;const pipe=new THREE.Mesh(new THREE.CylinderGeometry(radius,radius,sx*scale,64,1,true),wire);pipe.rotation.z=Math.PI/2;group.add(pipe)}
  else {const box=new THREE.Mesh(new THREE.BoxGeometry(sx*scale,sz*scale,sy*scale),wire);group.add(box)}
  scene.add(group);return group
}

export default function UnifiedField3D({result,running,resetKey}){
  const hostRef=useRef(null),resultRef=useRef(result),runningRef=useRef(running);const [error,setError]=useState('')
  useEffect(()=>{resultRef.current=result},[result]);useEffect(()=>{runningRef.current=running},[running])
  useEffect(()=>{const host=hostRef.current;if(!host||!result)return undefined;let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'})}catch(reason){setError(`无法初始化 WebGL：${reason.message}`);return undefined}
    renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setClearColor(0x060e19);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.domElement.setAttribute('aria-label',`${result.model} 三维求解场与粒子示踪`);host.appendChild(renderer.domElement)
    const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x060e19,.045);const camera=new THREE.PerspectiveCamera(42,1,.1,100);let azimuth=.75,elevation=.33,distance=10.5;const updateCamera=()=>{camera.position.set(Math.sin(azimuth)*Math.cos(elevation)*distance,Math.sin(elevation)*distance,Math.cos(azimuth)*Math.cos(elevation)*distance);camera.lookAt(0,0,0)};updateCamera()
    const grid=new THREE.GridHelper(9,18,0x35546d,0x183047);grid.position.y=-3.2;grid.material.transparent=true;grid.material.opacity=.34;scene.add(grid)
    const source=resultRef.current,values=source.particles.map(p=>p.value).filter(Number.isFinite),vmin=Math.min(...values),vmax=Math.max(...values),positions=new Float32Array(source.particles.length*3),colors=new Float32Array(source.particles.length*3),base=new Float32Array(source.particles.length*3),directions=new Float32Array(source.particles.length*3)
    source.particles.forEach((p,i)=>{const pos=displayPoint(p,source.bounds);base.set(pos,i*3);positions.set(pos,i*3);writeColor(colors,i,(p.value-vmin)/Math.max(1e-12,vmax-vmin));directions.set(normalizeVector(p.vx||0,p.vz||0,p.vy||0),i*3)})
    const geometry=new THREE.BufferGeometry(),positionAttribute=new THREE.BufferAttribute(positions,3);geometry.setAttribute('position',positionAttribute);geometry.setAttribute('color',new THREE.BufferAttribute(colors,3));const material=new THREE.PointsMaterial({size:.045,vertexColors:true,transparent:true,opacity:.85,depthWrite:false,blending:THREE.AdditiveBlending});scene.add(new THREE.Points(geometry,material));const modelGeometry=geometryFor(source.model,scene,source.bounds)
    // 托卡马克装置外壳采用用户指定的 tokamak-3d GLB 几何；计算场仍由 PhyTwin 求解器独立生成。
    let disposed=false
    if(source.model==='plasma'){new GLTFLoader().load('/tokamak.glb',gltf=>{const device=gltf.scene;if(disposed){device.traverse(object=>{object.geometry?.dispose();object.material?.dispose()});return}const box=new THREE.Box3().setFromObject(device),size=box.getSize(new THREE.Vector3()),center=box.getCenter(new THREE.Vector3()),fit=6/Math.max(size.x,size.y,size.z);device.position.sub(center);device.scale.setScalar(fit);device.rotation.x=-Math.PI/2;device.traverse(object=>{if(!object.isMesh)return;object.material=object.material.clone();object.material.transparent=true;object.material.opacity=.18;object.material.depthWrite=false});scene.add(device)},()=>{},()=>{})}
    const resize=()=>{const rect=host.getBoundingClientRect();renderer.setSize(Math.max(1,rect.width),Math.max(1,rect.height),false);camera.aspect=rect.width/Math.max(1,rect.height);camera.updateProjectionMatrix()},observer=new ResizeObserver(resize);observer.observe(host);resize();const pointer={down:false,x:0,y:0},down=e=>{pointer.down=true;pointer.x=e.clientX;pointer.y=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)},move=e=>{if(!pointer.down)return;azimuth-=(e.clientX-pointer.x)*.006;elevation=Math.max(-.65,Math.min(.78,elevation+(e.clientY-pointer.y)*.005));pointer.x=e.clientX;pointer.y=e.clientY;updateCamera()},up=()=>{pointer.down=false},wheel=e=>{e.preventDefault();distance=Math.max(6.8,Math.min(17,distance+e.deltaY*.008));updateCamera()};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',up);renderer.domElement.addEventListener('pointercancel',up);renderer.domElement.addEventListener('wheel',wheel,{passive:false})
    let frame=0,last=performance.now(),phase=0;const animate=now=>{frame=requestAnimationFrame(animate);const dt=Math.min(.035,(now-last)/1000);last=now;if(runningRef.current)phase+=dt;for(let i=0;i<positions.length/3;i++){const j=i*3,travel=(phase*(.18+(i%17)/90)+i*.071)%1-.5,amplitude=source.model==='em'?0:source.model==='thermal'?.1:.55;positions[j]=base[j]+directions[j]*travel*amplitude;positions[j+1]=base[j+1]+directions[j+1]*travel*amplitude;positions[j+2]=base[j+2]+directions[j+2]*travel*amplitude}positionAttribute.needsUpdate=true;if(source.model==='plasma')modelGeometry.rotation.y+=dt*.06;renderer.render(scene,camera)};frame=requestAnimationFrame(animate)
    return()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();renderer.domElement.removeEventListener('pointerdown',down);renderer.domElement.removeEventListener('pointermove',move);renderer.domElement.removeEventListener('pointerup',up);renderer.domElement.removeEventListener('pointercancel',up);renderer.domElement.removeEventListener('wheel',wheel);scene.traverse(object=>{object.geometry?.dispose();if(Array.isArray(object.material))object.material.forEach(m=>m.dispose());else object.material?.dispose()});renderer.dispose();renderer.domElement.remove()}
  },[result,resetKey])
  return <div className="unified-field-host" ref={hostRef}>{error&&<div className="webgl-error">{error}</div>}</div>
}
